# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/ibm-watson-cxa/EOCore.git'
source 'https://github.com/ibm-watson-cxa/DigitalAnalytics.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftDigitalAnalyticsPages' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDigitalAnalyticsPages

   pod 'DigitalAnalytics'

  target 'SwiftDigitalAnalyticsPagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDigitalAnalyticsPagesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
